function [xCOG,yCOG] = CentreOfGravity(grayImage)
% Calculate Centre of Gravity of binar image
% Auto-generated by colorThresholder app on 24-Mar-2022
%------------------------------------------------------

imshow(grayImage);
sumgx = 0;
sumgy = 0;
sumg = 0;
for col = 1 : size(1,2)+1
    for row = 1 : size(1,1)+1
        gl = double(grayImage(row, col));
        sumg = sumg + gl;
        sumgx = sumgx + col * gl;
        sumgy = sumgy + row * gl;
    end
end
xCOG = sumgx / sumg

yCOG = sumgy / sumg
end